/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockOracle__factory } from "./MockOracle__factory";
export { OracleSimple__factory } from "./OracleSimple__factory";
