/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DchainFixedStakingInterface extends utils.Interface {
  functions: {
    "Pause()": FunctionFragment;
    "TEN_MINUTES()": FunctionFragment;
    "UnPause()": FunctionFragment;
    "admin()": FunctionFragment;
    "baseInterestPerPeriod()": FunctionFragment;
    "claimReward(uint256)": FunctionFragment;
    "commissionInterestLevels(uint256)": FunctionFragment;
    "createStakingContract(uint256,address)": FunctionFragment;
    "cycleDuration()": FunctionFragment;
    "getF1Invited(address)": FunctionFragment;
    "interestIncreasePerCycle()": FunctionFragment;
    "joinByReferral(address)": FunctionFragment;
    "maxInterestPerPeriod()": FunctionFragment;
    "minimumStakingAmount()": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingReward(address,uint256)": FunctionFragment;
    "periodDuration()": FunctionFragment;
    "poolStatus()": FunctionFragment;
    "referralInvitationsByCommissionLevel(address,uint256)": FunctionFragment;
    "referredBy(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "rewardToken()": FunctionFragment;
    "totalReferralInvitations(address)": FunctionFragment;
    "totalStaked()": FunctionFragment;
    "totalStakingContracts()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasury()": FunctionFragment;
    "updateAdmin(address)": FunctionFragment;
    "updateTreasury(address)": FunctionFragment;
    "userInterestCommissions(address)": FunctionFragment;
    "userStakingContracts(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "Pause"
      | "TEN_MINUTES"
      | "UnPause"
      | "admin"
      | "baseInterestPerPeriod"
      | "claimReward"
      | "commissionInterestLevels"
      | "createStakingContract"
      | "cycleDuration"
      | "getF1Invited"
      | "interestIncreasePerCycle"
      | "joinByReferral"
      | "maxInterestPerPeriod"
      | "minimumStakingAmount"
      | "oracle"
      | "owner"
      | "paused"
      | "pendingReward"
      | "periodDuration"
      | "poolStatus"
      | "referralInvitationsByCommissionLevel"
      | "referredBy"
      | "renounceOwnership"
      | "rewardToken"
      | "totalReferralInvitations"
      | "totalStaked"
      | "totalStakingContracts"
      | "transferOwnership"
      | "treasury"
      | "updateAdmin"
      | "updateTreasury"
      | "userInterestCommissions"
      | "userStakingContracts"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TEN_MINUTES",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "UnPause", values?: undefined): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseInterestPerPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "commissionInterestLevels",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createStakingContract",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "cycleDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getF1Invited",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "interestIncreasePerCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinByReferral",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxInterestPerPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStakingAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingReward",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "periodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralInvitationsByCommissionLevel",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "referredBy",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReferralInvitations",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakingContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userInterestCommissions",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userStakingContracts",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "Pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TEN_MINUTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UnPause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseInterestPerPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commissionInterestLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cycleDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getF1Invited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interestIncreasePerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinByReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxInterestPerPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStakingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralInvitationsByCommissionLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referredBy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReferralInvitations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakingContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userInterestCommissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userStakingContracts",
    data: BytesLike
  ): Result;

  events: {
    "Deposit(address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RewardCommissionPaid(address,address,uint256,uint256)": EventFragment;
    "RewardHarvested(address,uint256)": EventFragment;
    "StakingContractCreated(address,address,uint256,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Withdraw(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardCommissionPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardHarvested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakingContractCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface DepositEventObject {
  user: string;
  contractId: BigNumber;
  amount: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RewardCommissionPaidEventObject {
  origin: string;
  receiver: string;
  level: BigNumber;
  amount: BigNumber;
}
export type RewardCommissionPaidEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  RewardCommissionPaidEventObject
>;

export type RewardCommissionPaidEventFilter =
  TypedEventFilter<RewardCommissionPaidEvent>;

export interface RewardHarvestedEventObject {
  claimer: string;
  amount: BigNumber;
}
export type RewardHarvestedEvent = TypedEvent<
  [string, BigNumber],
  RewardHarvestedEventObject
>;

export type RewardHarvestedEventFilter = TypedEventFilter<RewardHarvestedEvent>;

export interface StakingContractCreatedEventObject {
  user: string;
  referrer: string;
  contractId: BigNumber;
  stakingAmount: BigNumber;
}
export type StakingContractCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  StakingContractCreatedEventObject
>;

export type StakingContractCreatedEventFilter =
  TypedEventFilter<StakingContractCreatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface WithdrawEventObject {
  user: string;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface DchainFixedStaking extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DchainFixedStakingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    TEN_MINUTES(overrides?: CallOverrides): Promise<[number]>;

    UnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    baseInterestPerPeriod(overrides?: CallOverrides): Promise<[number]>;

    claimReward(
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    commissionInterestLevels(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createStakingContract(
      amount: PromiseOrValue<BigNumberish>,
      referrer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cycleDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    getF1Invited(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    interestIncreasePerCycle(overrides?: CallOverrides): Promise<[number]>;

    joinByReferral(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    maxInterestPerPeriod(overrides?: CallOverrides): Promise<[number]>;

    minimumStakingAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingReward(
      _account: PromiseOrValue<string>,
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    periodDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    poolStatus(overrides?: CallOverrides): Promise<[boolean]>;

    referralInvitationsByCommissionLevel(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    referredBy(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<[string]>;

    totalReferralInvitations(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalStaked(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalStakingContracts(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    updateAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userInterestCommissions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    userStakingContracts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        totalStakes: BigNumber;
        totalWithdrawed: BigNumber;
        claimedInterest: BigNumber;
        lastUpdatedTime: BigNumber;
        lastTimeDeposited: BigNumber;
        lastTimeClaimed: BigNumber;
        created: boolean;
      }
    >;
  };

  Pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  TEN_MINUTES(overrides?: CallOverrides): Promise<number>;

  UnPause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  baseInterestPerPeriod(overrides?: CallOverrides): Promise<number>;

  claimReward(
    _contractId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  commissionInterestLevels(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createStakingContract(
    amount: PromiseOrValue<BigNumberish>,
    referrer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cycleDuration(overrides?: CallOverrides): Promise<BigNumber>;

  getF1Invited(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  interestIncreasePerCycle(overrides?: CallOverrides): Promise<number>;

  joinByReferral(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  maxInterestPerPeriod(overrides?: CallOverrides): Promise<number>;

  minimumStakingAmount(overrides?: CallOverrides): Promise<BigNumber>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingReward(
    _account: PromiseOrValue<string>,
    _contractId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

  poolStatus(overrides?: CallOverrides): Promise<boolean>;

  referralInvitationsByCommissionLevel(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  referredBy(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rewardToken(overrides?: CallOverrides): Promise<string>;

  totalReferralInvitations(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalStaked(overrides?: CallOverrides): Promise<BigNumber>;

  totalStakingContracts(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasury(overrides?: CallOverrides): Promise<string>;

  updateAdmin(
    _admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateTreasury(
    _treasury: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userInterestCommissions(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  userStakingContracts(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      totalStakes: BigNumber;
      totalWithdrawed: BigNumber;
      claimedInterest: BigNumber;
      lastUpdatedTime: BigNumber;
      lastTimeDeposited: BigNumber;
      lastTimeClaimed: BigNumber;
      created: boolean;
    }
  >;

  callStatic: {
    Pause(overrides?: CallOverrides): Promise<void>;

    TEN_MINUTES(overrides?: CallOverrides): Promise<number>;

    UnPause(overrides?: CallOverrides): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    baseInterestPerPeriod(overrides?: CallOverrides): Promise<number>;

    claimReward(
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    commissionInterestLevels(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createStakingContract(
      amount: PromiseOrValue<BigNumberish>,
      referrer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    cycleDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getF1Invited(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestIncreasePerCycle(overrides?: CallOverrides): Promise<number>;

    joinByReferral(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    maxInterestPerPeriod(overrides?: CallOverrides): Promise<number>;

    minimumStakingAmount(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingReward(
      _account: PromiseOrValue<string>,
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    poolStatus(overrides?: CallOverrides): Promise<boolean>;

    referralInvitationsByCommissionLevel(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    referredBy(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    rewardToken(overrides?: CallOverrides): Promise<string>;

    totalReferralInvitations(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStaked(overrides?: CallOverrides): Promise<BigNumber>;

    totalStakingContracts(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    updateAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    userInterestCommissions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userStakingContracts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        totalStakes: BigNumber;
        totalWithdrawed: BigNumber;
        claimedInterest: BigNumber;
        lastUpdatedTime: BigNumber;
        lastTimeDeposited: BigNumber;
        lastTimeClaimed: BigNumber;
        created: boolean;
      }
    >;
  };

  filters: {
    "Deposit(address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      contractId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositEventFilter;
    Deposit(
      user?: PromiseOrValue<string> | null,
      contractId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): DepositEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RewardCommissionPaid(address,address,uint256,uint256)"(
      origin?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      level?: null,
      amount?: null
    ): RewardCommissionPaidEventFilter;
    RewardCommissionPaid(
      origin?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      level?: null,
      amount?: null
    ): RewardCommissionPaidEventFilter;

    "RewardHarvested(address,uint256)"(
      claimer?: PromiseOrValue<string> | null,
      amount?: null
    ): RewardHarvestedEventFilter;
    RewardHarvested(
      claimer?: PromiseOrValue<string> | null,
      amount?: null
    ): RewardHarvestedEventFilter;

    "StakingContractCreated(address,address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      referrer?: PromiseOrValue<string> | null,
      contractId?: PromiseOrValue<BigNumberish> | null,
      stakingAmount?: null
    ): StakingContractCreatedEventFilter;
    StakingContractCreated(
      user?: PromiseOrValue<string> | null,
      referrer?: PromiseOrValue<string> | null,
      contractId?: PromiseOrValue<BigNumberish> | null,
      stakingAmount?: null
    ): StakingContractCreatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Withdraw(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawEventFilter;
    Withdraw(
      user?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    Pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    TEN_MINUTES(overrides?: CallOverrides): Promise<BigNumber>;

    UnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    baseInterestPerPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    claimReward(
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    commissionInterestLevels(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createStakingContract(
      amount: PromiseOrValue<BigNumberish>,
      referrer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cycleDuration(overrides?: CallOverrides): Promise<BigNumber>;

    getF1Invited(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interestIncreasePerCycle(overrides?: CallOverrides): Promise<BigNumber>;

    joinByReferral(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxInterestPerPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    minimumStakingAmount(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingReward(
      _account: PromiseOrValue<string>,
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    poolStatus(overrides?: CallOverrides): Promise<BigNumber>;

    referralInvitationsByCommissionLevel(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    referredBy(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rewardToken(overrides?: CallOverrides): Promise<BigNumber>;

    totalReferralInvitations(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalStaked(overrides?: CallOverrides): Promise<BigNumber>;

    totalStakingContracts(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    updateAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userInterestCommissions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userStakingContracts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    TEN_MINUTES(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UnPause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseInterestPerPeriod(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimReward(
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    commissionInterestLevels(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createStakingContract(
      amount: PromiseOrValue<BigNumberish>,
      referrer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cycleDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getF1Invited(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interestIncreasePerCycle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinByReferral(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxInterestPerPeriod(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumStakingAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingReward(
      _account: PromiseOrValue<string>,
      _contractId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    referralInvitationsByCommissionLevel(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    referredBy(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rewardToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalReferralInvitations(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalStaked(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalStakingContracts(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateTreasury(
      _treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userInterestCommissions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userStakingContracts(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
