/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dwSol from "./DW.sol";
export type { dwSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as mocks from "./mocks";
export type { mocks };
import type * as oracles from "./oracles";
export type { oracles };
import type * as proxy from "./proxy";
export type { proxy };
export type { DChainBase } from "./DChainBase";
export type { DWStaking } from "./DWStaking";
export type { DWVault } from "./DWVault";
export type { HelloWorld } from "./HelloWorld";
