/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dgeSol from "./DGE.sol";
export type { dgeSol };
import type * as dgwSol from "./DGW.sol";
export type { dgwSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as keepers from "./keepers";
export type { keepers };
import type * as libraries from "./libraries";
export type { libraries };
import type * as mocks from "./mocks";
export type { mocks };
import type * as oracles from "./oracles";
export type { oracles };
import type * as proxy from "./proxy";
export type { proxy };
export type { DChainBase } from "./DChainBase";
export type { DGEStaking } from "./DGEStaking";
export type { DGEVault } from "./DGEVault";
export type { DGWPayment } from "./DGWPayment";
export type { DGWStaking } from "./DGWStaking";
export type { DGWSwap } from "./DGWSwap";
export type { DGWVault } from "./DGWVault";
