/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from "./IERC20.sol";
export type { ierc20Sol };
import type * as pancake from "./pancake";
export type { pancake };
export type { IDChainStaking } from "./IDChainStaking";
export type { IDDXStaking } from "./IDDXStaking";
export type { IDDXVault } from "./IDDXVault";
export type { IERC173 } from "./IERC173";
export type { IKeeperCompatible } from "./IKeeperCompatible";
export type { IOracleSimple } from "./IOracleSimple";
export type { IRegister } from "./IRegister";
export type { IUncxTokenVesting } from "./IUncxTokenVesting";
export type { IVersioned } from "./IVersioned";
