/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC173 } from "./IERC173";
export type { IERC20 } from "./IERC20";
export type { IIDOPool } from "./IIDOPool";
export type { IKeeperCompatible } from "./IKeeperCompatible";
export type { IOracleSimple } from "./IOracleSimple";
export type { IPancakeFactory } from "./IPancakeFactory";
export type { IPancakePair } from "./IPancakePair";
export type { IRegister } from "./IRegister";
export type { IVersioned } from "./IVersioned";
