/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeeperCompatible,
  IKeeperCompatibleInterface,
} from "../../../contracts/interfaces/IKeeperCompatible";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "checkData",
        type: "bytes",
      },
    ],
    name: "checkUpkeep",
    outputs: [
      {
        internalType: "bool",
        name: "upkeepNeeded",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKeeperCompatible__factory {
  static readonly abi = _abi;
  static createInterface(): IKeeperCompatibleInterface {
    return new utils.Interface(_abi) as IKeeperCompatibleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeeperCompatible {
    return new Contract(address, _abi, signerOrProvider) as IKeeperCompatible;
  }
}
