/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRegister,
  IRegisterInterface,
} from "../../../contracts/interfaces/IRegister";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
    ],
    name: "register",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRegister__factory {
  static readonly abi = _abi;
  static createInterface(): IRegisterInterface {
    return new utils.Interface(_abi) as IRegisterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegister {
    return new Contract(address, _abi, signerOrProvider) as IRegister;
  }
}
