/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_421614 = {
  DW_STAKING_PROXY: '0xd817dc637D7c7885c890827572467DEcf124bCec',
  usdcAddress: '0xb8206796F7c9789b56162fdF67f0a954e477Df23',
  proxyAdmin: '0x7D562A692a68fAbda14372Be393250317c47d353'
}