/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DWOracle__factory } from "./DWOracle__factory";
export { OracleSimple__factory } from "./OracleSimple__factory";
