/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdcSol from "./USDC.sol";
export type { usdcSol };
export type { MockERC20 } from "./MockERC20";
export type { MockOracle } from "./MockOracle";
